package Vista;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author AlumnoT
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        // creamos el panel y lo añadimos a las pestanias
        JTabbedPane pestanias = new JTabbedPane();
        setLayout(new BorderLayout());

        JPanel panelSumar = new JPanel(),
                panelPass = new JPanel(),
                panelPass1 = new JPanel(),
                panelPass2 = new JPanel(),
                panelPass3 = new JPanel(),
                panelViaje = new JPanel();

         // componentes del panel 1
        //----- aqui creamos los componentes o elementos que aniadiremos al panel 1
        panelSumar.setLayout(new FlowLayout(FlowLayout.RIGHT, 280, 0));
        panelSumar.add(new JTextField(8));
        panelSumar.add(new JTextField(8));
        panelSumar.add(new JButton("Aceptar"));

        panelPass.setLayout(new GridLayout(4, 3));

        panelPass1.setLayout(new FlowLayout(FlowLayout.RIGHT, 45, 0));
        panelPass2.setLayout(new FlowLayout(FlowLayout.RIGHT, 45, 0));
        panelPass3.setLayout(new FlowLayout(FlowLayout.LEFT, 30, 0));

        panelPass1.add(new JLabel("Usuario"));
        panelPass1.add(new JTextField(20));
        panelPass2.add(new JLabel("Contraseña"));
        panelPass2.add(new JTextField(20));
        panelPass3.add(new JButton("Login"));
        panelPass3.add(new JButton("Regresar"));

        panelPass.add(panelPass1);
        panelPass.add(panelPass2);
        panelPass.add(panelPass3);
        panelPass.add(new JPanel());

        pestanias.add("Sumar", panelSumar);
        pestanias.add("Usuario", panelPass);
        pestanias.add("Viajes", panelViaje);
        add(pestanias);

        setSize(400, 300);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
