package menuBarColores;

//http://www.tutorialesprogramacionya.com/javaya/detalleconcepto.php?codigo=110&punto=&inicio=

import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

//Declaramos la clase vistaColores, heredamos de la clase JFrame e indicamos que implementaremos la interface ActionListener:
public class vistaColores extends JFrame implements ActionListener {

    // Objeto de la clase JMenuBar (no importa como de grande sea un menú de opciones; solo se necesita un solo objeto de esta clase)
    private JMenuBar menu_bar;
    // Objeto de la clase JMenu (esta clase tiene por objeto desplegar un conjunto de objetos de tipo JMenuItem u otros objetos de tipo JMenu
    private JMenu menu1;
    // Definimos tres Objetos de la clase JMenuItem (estos son los que disparan eventos cuando el operador los selecciona
    private JMenuItem menuItem1, menuItem2, menuItem3;

    public vistaColores() {
        initComponents();

        setLayout(null);
        // En el constructor creamos primero el objeto de la clase JMenuBar y lo asociamos al JFrame llamando al método setJMenuBar
        menu_bar = new JMenuBar();
        setJMenuBar(menu_bar);

        /**
         * Seguidamente creamos un objeto de la clase JMenu, en el constructor
         * pasamos el String que debe mostrar y asociamos dicho JMenu con el
         * JMenuBar llamando al método add de objeto de tipo JMenuBar (Es decir
         * el objeto de la clase JMenu colabora con la clase JMenuBar)
         */
        menu1 = new JMenu("Opciones");
        menu_bar.add(menu1);

        /**
         * Ahora comenzamos a crear los objetos de la clase JMenuItem y los
         * añadimos al objeto de la clase JMenu (también mediante la llamada al
         * método addActionListener indicamos al JMenuItem que objeto procesará
         * el clic)
         */
        menuItem1 = new JMenuItem("Rojo");
        menuItem1.addActionListener(this);
        menu1.add(menuItem1);
        menuItem2 = new JMenuItem("Verde"); // y lo mismo para los otros menuItem
        menuItem2.addActionListener(this);
        menu1.add(menuItem2);
        menuItem3 = new JMenuItem("Azul");
        menuItem3.addActionListener(this);
        menu1.add(menuItem3);
    }

    //obtenemos la referencia al panel asociado con el JFrame
    public void actionPerformed(ActionEvent e) {
        Container f = this.getContentPane();
        /**
         * Mediante el bucle verificamos cual de los tres JMenuItem fue seleccionado y a partir de
         * esto llamamos al método setBackground del objeto de la clase
         * Container
         */
        if (e.getSource() == menuItem1) {
            f.setBackground(new Color(255, 0, 0));
        }
        if (e.getSource() == menuItem2) {
            f.setBackground(new Color(0, 255, 0));
        }
        if (e.getSource() == menuItem3) {
            f.setBackground(new Color(0, 0, 255));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        vistaColores formulario1 = new vistaColores();
        formulario1.setBounds(10, 20, 300, 200);
        formulario1.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
