/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TareaLibross;

import JTabla.MainTuto;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Panel;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AlumnoT
 */
public class Vista extends javax.swing.JFrame {

    JPanel p1;
    JPanel p2;
    JPanel p3;
    JPanel p4;
    JPanel p5;
    JPanel p6;
    JLabel l1;
    JLabel l2;
    JTextField txt;
    JTable table2;
    JTable table1;
    JScrollPane sp2;
    JScrollPane sp1;
    JButton b1;
    JButton b2;
    Object [][] datos2;
    Object [][] datos1;
    DefaultTableModel dtm2;
    DefaultTableModel dtm1;
    
    
    public Vista() {
        initComponents();
        setLayout(new GridLayout(2,1,0,0));
        
        p1 = new JPanel();
        p1.setLayout(new BorderLayout());
        
        p3 = new JPanel();
        p3.setLayout(new GridLayout(1,2,0,0));
        
        l2 = new JLabel("LIBROS: ");
        p3.add(l2);
        
        //Nombre de las columnas cabeceras
        String[] columNames = {"TITULO","AUTOR","Nº PAGINAS"};
        
        //UNIR LAS CABECERAS A LOS DATOS
        dtm1 = new DefaultTableModel(datos1,columNames);
        
        //Añado los datos2 a una tabla 
        table1 = new JTable(dtm1);
        
        sp1 = new JScrollPane(table1, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        sp1.setPreferredSize(new Dimension (150,150));
        
        p4 = new JPanel();
        p4.setLayout(new BorderLayout());
        b1 = new JButton("MOSTRAR");
        p4.add(b1, BorderLayout.EAST);
        
        p1.add(p3, BorderLayout.NORTH);
        p1.add(sp1, BorderLayout.CENTER);
        p1.add(p4, BorderLayout.SOUTH);
        
        add(p1);
        
        //SEGUNDA TABLA
        p2 = new JPanel();
        p2.setLayout(new BorderLayout());
        
        p5 = new JPanel();
        p5.setLayout(new GridLayout(1,2,0,0));
        l1 = new JLabel("ISBN DEL LIBRO: ");
        txt = new JTextField(10);
        p5.add(l1);
        p5.add(txt);
        
        //Nombre de las columnas cabeceras
        String[] columNames2 = {"TITULO","AUTOR","NºPAGINAS"};
        
        //UNIR LAS CABECERAS A LOS DATOS
        dtm2 = new DefaultTableModel(datos2,columNames2);
        
        //Añado los datos2 a una tabla 
        table2 = new JTable(dtm2);
        
        sp2 = new JScrollPane(table2, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        sp2.setPreferredSize(new Dimension (150,150));
        
        p6 = new JPanel();
        p6.setLayout(new BorderLayout());
        b2 = new JButton("BUSCAR");
        p6.add(b2, BorderLayout.EAST);
        
        p2.add(p5, BorderLayout.NORTH);
        p2.add(sp2, BorderLayout.CENTER);
        p2.add(p6, BorderLayout.SOUTH);
        
        add(p2);
        
        setSize(400, 400);
        setVisible(true);
    }
     public void conectaControlador(Controlador co){
        b1.addActionListener((ActionListener) co);
        b1.setActionCommand("MOSTRAR");
        b2.addActionListener((ActionListener) co);
        b2.setActionCommand("BUSCAR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

